//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Abc.Zebus;
using ProtoBuf;

#nullable enable

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = true)]
    public string StrNotNull { get; private set; }
    
    [ProtoMember(2, IsRequired = false)]
    public string? StrNull { get; private set; }
    
    [ProtoMember(3, IsRequired = false, IsPacked = true)]
    public int[] ArrayNotNull { get; private set; }
    
    [ProtoMember(4, IsRequired = false, IsPacked = true)]
    public int[]? ArrayNull { get; private set; }
    
    private FooExecuted()
    {
        StrNotNull = default!;
        ArrayNotNull = Array.Empty<int>();
    }
    
    public FooExecuted(string strNotNull, string? strNull, int[] arrayNotNull, int[]? arrayNull)
    {
        StrNotNull = strNotNull;
        StrNull = strNull;
        ArrayNotNull = arrayNotNull ?? Array.Empty<int>();
        ArrayNull = arrayNull;
    }
}
