//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = false, IsPacked = true)]
    public int[] Foo { get; private set; }
    
    [ProtoMember(2, IsRequired = false)]
    public LolType[] Bar { get; private set; }
    
    [ProtoMember(3, IsRequired = false, IsPacked = true)]
    public List<int> FooList { get; private set; }
    
    [ProtoMember(4, IsRequired = false)]
    public List<LolType> BarList { get; private set; }
    
    private FooExecuted()
    {
        Foo = Array.Empty<int>();
        Bar = Array.Empty<LolType>();
        FooList = new List<int>();
        BarList = new List<LolType>();
    }
    
    public FooExecuted(int[] foo, LolType[] bar, List<int> fooList, List<LolType> barList)
    {
        Foo = foo ?? Array.Empty<int>();
        Bar = bar ?? Array.Empty<LolType>();
        FooList = fooList;
        BarList = barList;
    }
}
