//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooMessage : BarMessage, IEvent
{
    [ProtoMember(1, IsRequired = true)]
    public int FooA { get; private set; }
    
    [ProtoMember(2, IsRequired = true)]
    public int BarA { get; private set; }
    
    private FooMessage()
    {
    }
    
    public FooMessage(int fooC, int barC, int fooB, int barB, int fooA, int barA = 10)
        : base(fooC, barC, fooB, barB)
    {
        FooA = fooA;
        BarA = barA;
    }
}

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public abstract partial class BarMessage : BazMessage, IEvent
{
    [ProtoMember(1, IsRequired = true)]
    public int FooB { get; private set; }
    
    [ProtoMember(2, IsRequired = true)]
    public int BarB { get; private set; }
    
    protected BarMessage()
    {
    }
    
    protected BarMessage(int fooC, int barC = 30, int fooB = 20, int barB = 21)
        : base(fooC, barC)
    {
        FooB = fooB;
        BarB = barB;
    }
}

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public abstract partial class BazMessage : IEvent
{
    [ProtoMember(1, IsRequired = true)]
    public int FooC { get; private set; }
    
    [ProtoMember(2, IsRequired = true)]
    public int BarC { get; private set; }
    
    protected BazMessage()
    {
    }
    
    protected BazMessage(int fooC, int barC = 30)
    {
        FooC = fooC;
        BarC = barC;
    }
}
