//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = true)]
    [ProtoMap(DisableMap = true)]
    public Dictionary<string, int> FooDico { get; private set; }
    
    private FooExecuted()
    {
        FooDico = new Dictionary<string, int>();
    }
    
    public FooExecuted(Dictionary<string, int> fooDico)
    {
        FooDico = fooDico;
    }
}
