//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = true)]
    [ProtoMap(DisableMap = true)]
    public Dictionary<int, string> Foo { get; private set; }
    
    private FooExecuted()
    {
        Foo = new Dictionary<int, string>();
    }
    
    public FooExecuted(Dictionary<int, string> foo)
    {
        Foo = foo;
    }
}
