//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class @void<@float> : IEvent
    where @float : @volatile
{
    [ProtoMember(1, IsRequired = true)]
    public int Double { get; private set; }
    
    [ProtoMember(2, IsRequired = true)]
    public @if Else { get; private set; }
    
    private @void()
    {
    }
    
    public @void(int @double, @if @else)
    {
        Double = @double;
        Else = @else;
    }
}
