//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = false)]
    public HashSet<string> FooHashSet { get; private set; }
    
    private FooExecuted()
    {
        FooHashSet = new HashSet<string>();
    }
    
    public FooExecuted(HashSet<string> fooHashSet)
    {
        FooHashSet = fooHashSet;
    }
}
