//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public abstract partial class FooExecuted : IEvent
{
    [ProtoMember(1, IsRequired = true)]
    public int Foo { get; private set; }
    
    [ProtoMember(2, IsRequired = true)]
    public int Bar { get; private set; }
    
    protected FooExecuted()
    {
    }
    
    protected FooExecuted(int foo, int bar)
    {
        Foo = foo;
        Bar = bar;
    }
}
