//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Abc.Zebus;
using ProtoBuf;

[ProtoContract]
[System.Diagnostics.DebuggerNonUserCode]
[System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.2.3.4")]
public sealed partial class Foo : IEvent
{
    [ProtoMember(1, IsRequired = false, IsPacked = true)]
    public int[] Bar { get; private set; }
    
    [ProtoMember(2, IsRequired = false)]
    public int?[] Bar2 { get; private set; }
    
    [ProtoMember(3, IsRequired = false)]
    public string[]? Baz { get; private set; }
    
    [ProtoMember(4, IsRequired = false)]
    public string?[] Baz2 { get; private set; }
    
    private Foo()
    {
        Bar = Array.Empty<int>();
        Bar2 = Array.Empty<int?>();
        Baz2 = Array.Empty<string?>();
    }
    
    public Foo(int[] bar, int?[] bar2, string[]? baz, string?[] baz2)
    {
        Bar = bar ?? Array.Empty<int>();
        Bar2 = bar2 ?? Array.Empty<int?>();
        Baz = baz;
        Baz2 = baz2 ?? Array.Empty<string?>();
    }
}
