using NUnit.Framework;

namespace Abc.Zebus.MessageDsl.Tool.Tests;

public class ToolTests
{
    private TextWriter _originalOut = null!;
    private TextReader _originalIn = null!;

    [SetUp]
    public void Setup()
    {
        _originalOut = Console.Out;
        _originalIn = Console.In;
    }

    [TearDown]
    public void TearDown()
    {
        Console.SetOut(_originalOut);
        Console.SetIn(_originalIn);
    }

    [Test]
    public void should_generate_csharp_with_namespace()
    {
        string inputContent = "TestMessage";
        string[] args = new[] { "--namespace", "TestNS", "--format", "CSharp" };
        var output = new StringWriter();
        Console.SetOut(output);
        Console.SetIn(new StringReader(inputContent));

        Program.Main(args);

        Assert.That(output.ToString(),
                    Is.EqualTo("""
                               //------------------------------------------------------------------------------
                               // <auto-generated>
                               //     This code was generated by a tool.
                               // </auto-generated>
                               //------------------------------------------------------------------------------

                               using System;
                               using Abc.Zebus;
                               using ProtoBuf;

                               namespace TestNS
                               {
                                   [ProtoContract]
                                   [System.Diagnostics.DebuggerNonUserCode]
                                   [System.CodeDom.Compiler.GeneratedCode("Abc.Zebus.MessageDsl", "1.5.0.0")]
                                   public sealed partial class TestMessage : IEvent
                                   {
                                   }
                               }

                               """));
    }

    [Test]
    public void should_generate_proto_output_with_empty_namespace_when_not_provided()
    {
        string fileContent = "TestMessage";
        string tempFile = Path.GetTempFileName();
        try
        {
            File.WriteAllText(tempFile, fileContent);
            string[] args = new[] { tempFile, "--format", "Proto" };
            var output = new StringWriter();
            Console.SetOut(output);

            Program.Main(args);

            Assert.That(output.ToString(),
                        Is.EqualTo("""

                                   // Generated by Abc.Zebus.MessageDsl v1.5.0.0

                                   import "servicebus.proto";

                                   message TestMessage {
                                       option (servicebus.message).type = Event;

                                   }

                                   """
                        ));
        }
        finally
        {
            File.Delete(tempFile);
        }
    }
}
