<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>$schema</key>
        <string>
            https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json
        </string>
        <key>name</key>
        <string>Zebus Messages</string>
        <key>uuid</key>
        <string>86FA8B6A-FA5E-4139-904B-91C75675BC6B</string>
        <key>scopeName</key>
        <string>source.zebusmsg</string>
        <key>fileTypes</key>
        <array>
            <string>msg</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#messages</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>messages</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#comments</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#pragma</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#attributes</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#messageName</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#keywords</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#literals</string>
                    </dict>
                </array>
            </dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.block.zebusmsg</string>
                        <key>begin</key>
                        <string>/\*</string>
                        <key>end</key>
                        <string>\*/</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#commentContent</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>comment.line</string>
                        <key>begin</key>
                        <string>//</string>
                        <key>end</key>
                        <string>$</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#commentContent</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>commentContent</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.control</string>
                        <key>match</key>
                        <string>(?i)\b(TODO|FIXME|HACK|ISSUE)\b</string>
                    </dict>
                </array>
            </dict>
            <key>pragma</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>meta.preprocessor.zebusmsg</string>
                        <key>begin</key>
                        <string>^\s*#\s*\pragma\b</string>
                        <key>end</key>
                        <string>$</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#comments</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>attributes</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>emphasis</string>
                        <key>begin</key>
                        <string>\[</string>
                        <key>end</key>
                        <string>\]</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#attributes</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#comments</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#keywords</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#literals</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>messageName</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>entity.name.class.zebusmsg</string>
                        <key>match</key>
                        <string>\w+(?=\s*[(&lt;])</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.zebusmsg</string>
                        <key>match</key>
                        <string>\w+(?=\s*!\s*\()</string>
                    </dict>
                </array>
            </dict>
            <key>keywords</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.zebusmsg</string>
                        <key>match</key>
                        <string>
                            \b(this|base|as|is|new|sizeof|typeof|stackalloc|true|false|else|if|switch|case|default|do|for|foreach|in|while|lock|break|continue|goto|return|try|throw|catch|finally|checked|unchecked|fixed|unsafe|class|interface|delegate|explicit|implicit|operator|params|ref|out|abstract|const|event|extern|override|readonly|sealed|static|virtual|volatile|public|protected|private|internal|namespace|using|get|set|add|remove|null|bool|byte|char|decimal|double|enum|float|int|long|sbyte|short|struct|uint|ushort|ulong|object|string|void|DateTime|Guid)\b
                        </string>
                    </dict>
                </array>
            </dict>
            <key>literals</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double.zebusmsg</string>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>name</key>
                                <string>
                                    constant.character.escape.zebusmsg
                                </string>
                                <key>match</key>
                                <string>\\.</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double.zebusmsg</string>
                        <key>begin</key>
                        <string>@"</string>
                        <key>end</key>
                        <string>"(?!")</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>name</key>
                                <string>
                                    constant.character.escape.zebusmsg
                                </string>
                                <key>match</key>
                                <string>""</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.single.zebusmsg</string>
                        <key>match</key>
                        <string>'(\\.|.)'</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric</string>
                        <key>match</key>
                        <string>
                            \b0[xX][0-9a-fA-F]+|(\b\d+(\.[0-9]+)?|\.[0-9]+)([eE][+-]?[0-9]+)?
                        </string>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>
