
name: Build
on: [push, pull_request]

env:
  BUILD_DOTNET_VERSION: 8.0.x
  DOTNET_NOLOGO: 1

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore src/Abc.Zebus.MessageDsl.sln

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Abc.Zebus.MessageDsl.sln

      - name: Pack
        run: dotnet pack --configuration Release --no-build src/Abc.Zebus.MessageDsl.sln

      - name: Test
        run: dotnet test --configuration Release --no-build src/Abc.Zebus.MessageDsl.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: output/*.nupkg

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.BUILD_DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore src/Abc.Zebus.MessageDsl.sln

      - name: Build Tests
        run:  dotnet build --configuration Release --no-restore src/Abc.Zebus.MessageDsl.Tests/Abc.Zebus.MessageDsl.Tests.csproj

      - name: Build Integration
        run:  dotnet build --configuration Release --no-restore src/Abc.Zebus.MessageDsl.Build.Integration/Abc.Zebus.MessageDsl.Build.Integration.csproj

      - name: Generator Integration
        run:  dotnet build --configuration Release --no-restore src/Abc.Zebus.MessageDsl.Generator.Integration/Abc.Zebus.MessageDsl.Generator.Integration.csproj

      - name: Test
        run: dotnet test --configuration Release --no-build src/Abc.Zebus.MessageDsl.Tests/Abc.Zebus.MessageDsl.Tests.csproj
